force-app/main/default/objects/Connect__c/Connect__c.object-meta.xml
<CustomObject>
    <label>Connect</label>
    <nameField>
        <displayFormat>CON-{000000}</displayFormat>
        <label>Connect Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connect__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Answer</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Connect__c/fields/Initializer__c.field-meta.xml
<CustomField>
    <fullName>Initializer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Initializer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Connect__c/fields/Offer__c.field-meta.xml
<CustomField>
    <fullName>Offer__c</fullName>
    <label>Offer</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Connect__c/fields/Responder__c.field-meta.xml
<CustomField>
    <fullName>Responder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Responder</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Connections1</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/ForceRTC.cls
global class ForceRTC {

    public ForceRTC() {} // empty constructor
    
    @RemoteAction
    global static Connect__c mkConnection(String offer, String userId) {
        
        Connect__c conn = new Connect__c(
            Offer__c = offer,
            Responder__c = userId,
            Initializer__c = UserInfo.getUserId()
        );

        insert conn;
        
        return conn;
    }

    @RemoteAction
    global static Connect__c getConnection(String recId) {
        
        return [
            SELECT Id, Name, Answer__c, Offer__c, Initializer__c, Responder__c
            FROM Connect__c 
            WHERE Id = :recId
        ];
    }
    
    @RemoteAction
    global static Connect__c setAnswer(String recId, String answer) {
        
        Connect__c conn = [
            SELECT Id, Name, Answer__c, Offer__c, Initializer__c, Responder__c
            FROM Connect__c 
            WHERE Id = :recId
        ];

        conn.Answer__c = answer;

        update conn;

        return conn;
    }
    
    @RemoteAction
    global static List<User> getUsers() {
        // Normally User wouldn't connect to themselves but demo so...
        return [
            SELECT Id, Name, Email
            FROM User
            WHERE isActive = true
        ]; // AND Id != :UserInfo.getUserId()
    }
}